version: 1
disable_existing_loggers: False
formatters:
  uvicorn:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(asctime)s %(levelprefix)s uvicorn - %(message)s"
  access:
    (): "uvicorn.logging.AccessFormatter"
    fmt: '%(asctime)s %(levelprefix)s %(name)s - %(client_addr)s - "%(request_line)s" %(status_code)s'
  app:
    (): "uvicorn.logging.DefaultFormatter"
    fmt: "%(asctime)s %(levelprefix)s %(name)s - %(message)s"
handlers:
  uvicorn:
    class: logging.StreamHandler
    formatter: uvicorn
    stream: ext://sys.stderr
  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout
  app:
    class: logging.StreamHandler
    formatter: app
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: ERROR
    handlers:
      - uvicorn
  uvicorn.access:
    level: INFO
    handlers:
      - access
  langchain:
    level: ERROR
    handlers:
      - app
  utils:
    level: ERROR
    handlers:
      - app
  refinement:
    level: INFO
    handlers:
      - app
  summarization:
    level: INFO
    handlers:
      - app
  health:
    level: ERROR
    handlers:
      - app
