apiVersion: apps/v1
kind: Deployment
metadata:
  name: "###ZARF_PKG_TMPL_NAME###"
  namespace: leapfrogai
spec:
  selector:
    matchLabels:
      app: "###ZARF_PKG_TMPL_NAME###"
  replicas: 1
  template:
    metadata:
      labels:
        app: "###ZARF_PKG_TMPL_NAME###"
    spec:
      containers:
        - name: "###ZARF_PKG_TMPL_NAME###"
          image: "ghcr.io/defenseunicorns/leapfrogai/leapfrog-ui:###ZARF_VAR_IMAGE_VERSION###"
          ports:
            - containerPort: 3000
          env:
            - name: OPENAI_API_HOST
              value: "###ZARF_VAR_LEAPFROGAI_BASE_URL###"
            - name: RAG_API_HOST
              value: "###ZARF_VAR_LEAPFROGAI_RAG_URL###"
            - name: OPENAI_API_KEY
              value: "###ZARF_VAR_LEAPFROGAI_API_KEY###"
          resources:
            requests:
              memory: "5Gi"
              cpu: "500m"
            limits:
              memory: "5Gi"
              cpu: "1000m"
